name: Create Weekly Release Branch

on:
  schedule:
    - cron: '30 17 * * 5' # 毎週金曜日の17:30に実行

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get date one week from now
        id: date
        run: echo "::set-output name=date::$(date -d '+7 days' +'%Y%m%d')"

      - name: Create new branch
        run: |
          BRANCH_NAME=release-${{ steps.date.outputs.date }}
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
